version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL:-file:/app/data/prod.db}
      # Add your environment variables here or use an .env file
      - AUTH_SECRET=${AUTH_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - BASE_URL=${BASE_URL:-https://test.twink.forsale}
    volumes:
      # Persistent storage for uploads
      - uploads_data:/app/uploads
      # Persistent storage for SQLite database
      - db_data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  uploads_data:
  db_data: