packages:
  - frontend

packageExtensions:
  '@luminescent/ui@*':
    peerDependencies:
      tailwindcss: '*'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - diskusage
  - esbuild
  - prisma
  - sharp
