// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwinkForSale.Api.Data;

#nullable disable

namespace TwinkForSale.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwinkForSale.Api.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer");

                    b.Property<string>("IdToken")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("SessionState")
                        .HasColumnType("text");

                    b.Property<string>("TokenType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.BioLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Order");

                    b.ToTable("bio_links", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.BioView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ViewedAt");

                    b.HasIndex("IpAddress", "UserId", "ViewedAt");

                    b.ToTable("bio_views", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ClickLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("ClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<string>("ShortLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClickedAt");

                    b.HasIndex("ShortLinkId");

                    b.ToTable("click_logs", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.DailyAnalytics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueDownloads")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueViews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploadsCount")
                        .HasColumnType("integer");

                    b.Property<int>("UsersRegistered")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_analytics", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.DownloadLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("UploadId");

                    b.HasIndex("IpAddress", "UploadId", "DownloadedAt");

                    b.ToTable("download_logs", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ShortLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastClickedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxClicks")
                        .HasColumnType("integer");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("short_links", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.SystemAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastTriggered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotifyAdmins")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotifyUser")
                        .HasColumnType("boolean");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("system_alerts", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.SystemEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DiskUsage")
                        .HasColumnType("double precision");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("double precision");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.Upload", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletionKey")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.UploadDomain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsSubdomains")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("upload_domains", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.UserSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BioAccentColor")
                        .HasColumnType("text");

                    b.Property<string>("BioBackgroundColor")
                        .HasColumnType("text");

                    b.Property<string>("BioBackgroundImage")
                        .HasColumnType("text");

                    b.Property<string>("BioCustomCss")
                        .HasColumnType("text");

                    b.Property<string>("BioDescription")
                        .HasColumnType("text");

                    b.Property<string>("BioDiscordConfig")
                        .HasColumnType("text");

                    b.Property<string>("BioDiscordUserId")
                        .HasColumnType("text");

                    b.Property<string>("BioDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("BioGradientConfig")
                        .HasColumnType("text");

                    b.Property<bool>("BioIsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BioLastViewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BioParticleConfig")
                        .HasColumnType("text");

                    b.Property<string>("BioProfileImage")
                        .HasColumnType("text");

                    b.Property<bool>("BioShowDiscord")
                        .HasColumnType("boolean");

                    b.Property<string>("BioSpotifyTrack")
                        .HasColumnType("text");

                    b.Property<string>("BioTextColor")
                        .HasColumnType("text");

                    b.Property<string>("BioUsername")
                        .HasColumnType("text");

                    b.Property<int>("BioViews")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text");

                    b.Property<string>("CustomSubdomain")
                        .HasColumnType("text");

                    b.Property<string>("CustomWords")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultExpirationDays")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultMaxViews")
                        .HasColumnType("integer");

                    b.Property<string>("EmbedAuthor")
                        .HasColumnType("text");

                    b.Property<string>("EmbedColor")
                        .HasColumnType("text");

                    b.Property<string>("EmbedDescription")
                        .HasColumnType("text");

                    b.Property<string>("EmbedFooter")
                        .HasColumnType("text");

                    b.Property<string>("EmbedTitle")
                        .HasColumnType("text");

                    b.Property<string>("GlobalParticleConfig")
                        .HasColumnType("text");

                    b.Property<int?>("MaxBioLinks")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDescriptionLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDisplayNameLength")
                        .HasColumnType("integer");

                    b.Property<long>("MaxFileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("MaxIconLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLinkTitleLength")
                        .HasColumnType("integer");

                    b.Property<int>("MaxShortLinks")
                        .HasColumnType("integer");

                    b.Property<long?>("MaxStorageLimit")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxUploads")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUrlLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsernameLength")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowFileInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowUploadDate")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowUserStats")
                        .HasColumnType("boolean");

                    b.Property<long>("StorageUsed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadDomainId")
                        .HasColumnType("text");

                    b.Property<bool>("UseCustomWords")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BioUsername")
                        .IsUnique();

                    b.HasIndex("UploadDomainId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ViewLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Referrer")
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.HasIndex("ViewedAt");

                    b.HasIndex("IpAddress", "UploadId", "ViewedAt");

                    b.ToTable("view_logs", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.Account", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ApiKey", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.BioLink", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("BioLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.BioView", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("BioViews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ClickLog", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.ShortLink", "ShortLink")
                        .WithMany("ClickLogs")
                        .HasForeignKey("ShortLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShortLink");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.DownloadLog", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.Upload", "Upload")
                        .WithMany("DownloadLogs")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ShortLink", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("ShortLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.SystemEvent", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("SystemEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.Upload", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.User", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.User", "ApprovedBy")
                        .WithMany("ApprovedUsers")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedBy");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.UserSettings", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.UploadDomain", "UploadDomain")
                        .WithMany("UserSettings")
                        .HasForeignKey("UploadDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TwinkForSale.Api.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("TwinkForSale.Api.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadDomain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ViewLog", b =>
                {
                    b.HasOne("TwinkForSale.Api.Entities.Upload", "Upload")
                        .WithMany("ViewLogs")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.ShortLink", b =>
                {
                    b.Navigation("ClickLogs");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.Upload", b =>
                {
                    b.Navigation("DownloadLogs");

                    b.Navigation("ViewLogs");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.UploadDomain", b =>
                {
                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("TwinkForSale.Api.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ApiKeys");

                    b.Navigation("ApprovedUsers");

                    b.Navigation("BioLinks");

                    b.Navigation("BioViews");

                    b.Navigation("Settings");

                    b.Navigation("ShortLinks");

                    b.Navigation("SystemEvents");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
