// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwinkForSale.Api.Infrastructure.Database;

#nullable disable

namespace TwinkForSale.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701055351_InitialPostgresSchema")]
    partial class InitialPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("providerAccountId");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("SessionState")
                        .HasColumnType("text")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ApiKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastUsed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.BioLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Order");

                    b.ToTable("bio_links", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.BioView", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ipAddress");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("userAgent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewedAt");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ViewedAt");

                    b.HasIndex("IpAddress", "UserId", "ViewedAt");

                    b.ToTable("bio_views", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.DailyAnalytics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDownloads")
                        .HasColumnType("integer")
                        .HasColumnName("totalDownloads");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer")
                        .HasColumnName("totalViews");

                    b.Property<int>("UniqueDownloads")
                        .HasColumnType("integer")
                        .HasColumnName("uniqueDownloads");

                    b.Property<int>("UniqueViews")
                        .HasColumnType("integer")
                        .HasColumnName("uniqueViews");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<int>("UploadsCount")
                        .HasColumnType("integer")
                        .HasColumnName("uploadsCount");

                    b.Property<int>("UsersRegistered")
                        .HasColumnType("integer")
                        .HasColumnName("usersRegistered");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("daily_analytics", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.DownloadLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DownloadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("downloadedAt");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ipAddress");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploadId");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("userAgent");

                    b.HasKey("Id");

                    b.HasIndex("DownloadedAt");

                    b.HasIndex("UploadId");

                    b.HasIndex("IpAddress", "UploadId", "DownloadedAt");

                    b.ToTable("download_logs", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sessionToken");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ShortLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<DateTimeOffset?>("LastClicked")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastClicked");

                    b.Property<int?>("MaxClicks")
                        .HasColumnType("integer")
                        .HasColumnName("maxClicks");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("short_links", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.SystemAlert", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooldownMinutes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventType");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<DateTimeOffset?>("LastTriggered")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastTriggered");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotifyAdmins")
                        .HasColumnType("boolean")
                        .HasColumnName("notifyAdmins");

                    b.Property<bool>("NotifyUser")
                        .HasColumnType("boolean")
                        .HasColumnName("notifyUser");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("system_alerts", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.SystemEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double?>("CpuUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("cpuUsage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<double?>("DiskUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("diskUsage");

                    b.Property<double?>("MemoryUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("memoryUsage");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Severity");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("system_events", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Upload", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("DeletionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deletionKey");

                    b.Property<int>("Downloads")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresAt");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastDownloaded")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastDownloaded");

                    b.Property<DateTimeOffset?>("LastViewed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastViewed");

                    b.Property<int?>("MaxViews")
                        .HasColumnType("integer")
                        .HasColumnName("maxViews");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mimeType");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originalName");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shortCode");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeletionKey")
                        .IsUnique();

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("uploads", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.UploadDomain", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SupportsSubdomains")
                        .HasColumnType("boolean")
                        .HasColumnName("supportsSubdomains");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique();

                    b.ToTable("upload_domains", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approvedAt");

                    b.Property<string>("ApprovedById")
                        .HasColumnType("text")
                        .HasColumnName("approvedById");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailVerified");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("isAdmin");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("isApproved");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.UserSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BioAccentColor")
                        .HasColumnType("text");

                    b.Property<string>("BioBackgroundColor")
                        .HasColumnType("text");

                    b.Property<string>("BioBackgroundImage")
                        .HasColumnType("text");

                    b.Property<string>("BioCustomCss")
                        .HasColumnType("text");

                    b.Property<string>("BioDescription")
                        .HasColumnType("text");

                    b.Property<string>("BioDiscordConfig")
                        .HasColumnType("text");

                    b.Property<string>("BioDiscordUserId")
                        .HasColumnType("text");

                    b.Property<string>("BioDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("BioGradientConfig")
                        .HasColumnType("text");

                    b.Property<bool>("BioIsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("BioLastViewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BioParticleConfig")
                        .HasColumnType("text");

                    b.Property<string>("BioProfileImage")
                        .HasColumnType("text");

                    b.Property<bool>("BioShowDiscord")
                        .HasColumnType("boolean");

                    b.Property<string>("BioSpotifyTrack")
                        .HasColumnType("text");

                    b.Property<string>("BioTextColor")
                        .HasColumnType("text");

                    b.Property<string>("BioUsername")
                        .HasColumnType("text")
                        .HasColumnName("bioUsername");

                    b.Property<int>("BioViews")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text");

                    b.Property<string>("CustomSubdomain")
                        .HasColumnType("text");

                    b.Property<int?>("DefaultExpirationDays")
                        .HasColumnType("integer");

                    b.Property<int?>("DefaultMaxViews")
                        .HasColumnType("integer");

                    b.Property<string>("EmbedAuthor")
                        .HasColumnType("text");

                    b.Property<string>("EmbedColor")
                        .HasColumnType("text");

                    b.Property<string>("EmbedDescription")
                        .HasColumnType("text");

                    b.Property<string>("EmbedFooter")
                        .HasColumnType("text");

                    b.Property<string>("EmbedTitle")
                        .HasColumnType("text");

                    b.Property<string>("GlobalParticleConfig")
                        .HasColumnType("text");

                    b.Property<int?>("MaxBioLinks")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDescriptionLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxDisplayNameLength")
                        .HasColumnType("integer");

                    b.Property<long>("MaxFileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("maxFileSize");

                    b.Property<int?>("MaxIconLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxLinkTitleLength")
                        .HasColumnType("integer");

                    b.Property<int>("MaxShortLinks")
                        .HasColumnType("integer")
                        .HasColumnName("maxShortLinks");

                    b.Property<long?>("MaxStorageLimit")
                        .HasColumnType("bigint")
                        .HasColumnName("maxStorageLimit");

                    b.Property<int>("MaxUploads")
                        .HasColumnType("integer")
                        .HasColumnName("maxUploads");

                    b.Property<int?>("MaxUrlLength")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsernameLength")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowFileInfo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowUploadDate")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowUserStats")
                        .HasColumnType("boolean");

                    b.Property<long>("StorageUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("storageUsed");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadDomainId")
                        .HasColumnType("text")
                        .HasColumnName("uploadDomainId");

                    b.Property<bool>("UseCustomWords")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("BioUsername")
                        .IsUnique();

                    b.HasIndex("UploadDomainId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.VerificationToken", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Identifier", "Token");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("verificationtokens", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ViewLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ipAddress");

                    b.Property<string>("Referer")
                        .HasColumnType("text");

                    b.Property<string>("UploadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uploadId");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("userAgent");

                    b.Property<DateTimeOffset>("ViewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("viewedAt");

                    b.HasKey("Id");

                    b.HasIndex("UploadId");

                    b.HasIndex("ViewedAt");

                    b.HasIndex("IpAddress", "UploadId", "ViewedAt");

                    b.ToTable("view_logs", (string)null);
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Account", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.BioLink", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("BioLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.BioView", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("BioViewLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.DownloadLog", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.Upload", "Upload")
                        .WithMany("DownloadLogs")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Session", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ShortLink", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("ShortLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.SystemEvent", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("SystemEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Upload", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithMany("Uploads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "ApprovedBy")
                        .WithMany("ApprovedUsers")
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApprovedBy");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.UploadDomain", "UploadDomain")
                        .WithMany("UserSettings")
                        .HasForeignKey("UploadDomainId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TwinkForSale.Api.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("TwinkForSale.Api.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadDomain");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.ViewLog", b =>
                {
                    b.HasOne("TwinkForSale.Api.Domain.Entities.Upload", "Upload")
                        .WithMany("ViewLogs")
                        .HasForeignKey("UploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.Upload", b =>
                {
                    b.Navigation("DownloadLogs");

                    b.Navigation("ViewLogs");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.UploadDomain", b =>
                {
                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("TwinkForSale.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("ApiKeys");

                    b.Navigation("ApprovedUsers");

                    b.Navigation("BioLinks");

                    b.Navigation("BioViewLogs");

                    b.Navigation("Sessions");

                    b.Navigation("Settings");

                    b.Navigation("ShortLinks");

                    b.Navigation("SystemEvents");

                    b.Navigation("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
